---
- name: Create www directory
  file:
    path: "{{ www_dir }}"
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data

- name: Copy built site to www directory
  shell: |
    rsync -av --delete {{ project_dir }}/public/ {{ www_dir }}/
    chown -R www-data:www-data {{ www_dir }}
    chmod -R 755 {{ www_dir }}

- name: Clean up temporary directory
  file:
    path: "{{ project_dir }}"
    state: absent
