---
- name: Create temporary project directory
  file:
    path: "{{ project_dir }}"
    state: directory
    mode: '0755'

- name: Copy project files to server
  copy:
    src: "{{ item }}"
    dest: "{{ project_dir }}/{{ item }}"
  loop:
    - config.toml
    - content
    - static
    - templates
